Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-1204"
  config.vm.box_url = "http://vagrantbox.desarrollo.cespi.unlp.edu.ar/pub/ubuntu-12.04.2-cespi-amd64.box"
  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = "cookbooks"
     chef.add_recipe "ntp"
#     chef.json = { 
#       :ntp => {
#          :server => "cronos.unlp.edu.ar"
#       }
#     }
  end
end
